COMPONENT=Homechallenge1C
#BUILD_EXTRA_DEPS = RadioCountMsg.py RadioCountMsg.class
#CLEAN_EXTRA = RadioCountMsg.py RadioCountMsg.class RadioCountMsg.java

#RadioCountMsg.py: Homechallenge1.h
#	mig python -target=$(PLATFORM) $(CFLAGS) -python-classname=RadioCountMsg Homechallenge1.h radio_count_msg -o $@

#RadioCountMsg.class: RadioCountMsg.java
#	javac RadioCountMsg.java

#RadioCountMsg.java: Homechallenge1.h
#	mig java -target=$(PLATFORM) $(CFLAGS) -java-classname=RadioCountMsg Homechallenge1.h radio_count_msg -o $@


include $(MAKERULES)


